/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package activity13;

import java.awt.Image;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author L27X14W32
 */
public class Game extends javax.swing.JFrame {
    
    int playerHp = 100;
    int compHp = 100;
    int playerChoice = 0;
    int comChoice = 0;
    int playerWins = 0;
    int compWins = 0;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        btnRock = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnScissors = new javax.swing.JButton();
        btnFight = new javax.swing.JButton();
        lblWin = new javax.swing.JLabel();
        lblPlayerWins = new javax.swing.JLabel();
        lblPlayerPick = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblComWins = new javax.swing.JLabel();
        lblComp = new javax.swing.JLabel();
        lblComputerPick = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        prgPlayerLife = new javax.swing.JProgressBar();
        prgComputerLife = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jack n' Poy");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblName.setText("PLAYER");

        btnRock.setText("R");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        btnPaper.setText("P");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        btnScissors.setText("S");
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });

        btnFight.setText("FIGHT!");
        btnFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFightActionPerformed(evt);
            }
        });

        lblWin.setText("Win");

        lblPlayerWins.setText("0");

        lblName2.setText("COMPUTER");

        lblComWins.setText("0");

        lblComp.setText("Win");

        btnReset.setText("RESET GAME");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFight, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prgPlayerLife, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prgComputerLife, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPlayerWins)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblComWins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblComp))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayerPick, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(lblComputerPick, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prgPlayerLife, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(prgComputerLife, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWin)
                    .addComponent(lblPlayerWins)
                    .addComponent(lblComWins)
                    .addComponent(lblComp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComputerPick, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(lblPlayerPick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnScissors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //prgComputerLife.setValue(compHp);
        //prgPlayerLife.setValue(playerHp);
        ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\choice.gif");
        Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
        lblPlayerPick.setIcon(new ImageIcon(img));
        
        prgPlayerLife.setValue(playerHp);
        prgComputerLife.setValue(compHp);
        
        btnFight.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        // TODO add your handling code here:
        btnFight.setEnabled(true);
        playerChoice = 1;
        ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\rock.gif");
        Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
        lblPlayerPick.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_btnRockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        // TODO add your handling code here:
        btnFight.setEnabled(true);
        playerChoice = 2;
        ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\paper.gif");
        Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
        lblPlayerPick.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed
        // TODO add your handling code here:
        btnFight.setEnabled(true);
        playerChoice = 3;
        ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\scissors.gif");
        Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
        lblPlayerPick.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_btnScissorsActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFightActionPerformed
        // TODO add your handling code here:
        Random rnd = new Random();
        comChoice = rnd.nextInt(3) + 1;
        if(comChoice == 1) {
            ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\rock.gif");
            Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
            lblComputerPick.setIcon(new ImageIcon(img));
        } else if(comChoice == 2) {
            ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\paper.gif");
            Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
            lblComputerPick.setIcon(new ImageIcon(img));
        } else if(comChoice == 3) {
            ImageIcon pic = new ImageIcon("C:\\Users\\L27X14W32\\Documents\\NetBeansProjects\\Activity13\\src\\images\\scissors.gif");
            Image img = pic.getImage().getScaledInstance(lblPlayerPick.getWidth(), lblPlayerPick.getHeight(), Image.SCALE_DEFAULT);
            lblPlayerPick.setIcon(new ImageIcon(img));
        }
        
        
        //Checker Player
        if(playerChoice == 1 && comChoice == 1 || playerChoice == 2 && comChoice == 2 || playerChoice == 3 && comChoice == 3){
            JOptionPane.showMessageDialog(null, "It's a tie!", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
        }else if(playerChoice==1&&comChoice==3||playerChoice==2&&comChoice==1||playerChoice==3&&comChoice==2){
            JOptionPane.showMessageDialog(null, "You Won!", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
            compHp-=50;
            prgComputerLife.setValue(compHp);
            if(prgComputerLife.getValue() == 0 ){
                JOptionPane.showMessageDialog(null, "You Won!, Reset The game.", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
                playerWins++;
                compHp=100;
                playerHp=100;
                prgComputerLife.setValue(compHp);
                prgPlayerLife.setValue(playerHp);
                lblPlayerWins.setText(playerWins+"");
            }else if(prgPlayerLife.getValue() == 0 ){
                JOptionPane.showMessageDialog(null, "You Lost!, Reset The game.", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
                compHp=100;
                compWins++;
                playerHp=100;
                prgComputerLife.setValue(compHp);
                lblComWins.setText(compWins+"");
                prgPlayerLife.setValue(playerHp);
            }
        }else if(playerChoice==1&&comChoice==2||playerChoice==2&&comChoice==3||playerChoice==3&&comChoice==1){
            JOptionPane.showMessageDialog(null, "You Lost!", "Jack n' Poy Game", JOptionPane.WARNING_MESSAGE);
            playerHp-=50;
            prgPlayerLife.setValue(playerHp);
            if(prgComputerLife.getValue() == 0 ){
                JOptionPane.showMessageDialog(null, "You Won!, Reset The game.", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
                compHp=100;
                playerHp=100;
                playerWins++;
                lblPlayerWins.setText(playerWins+"");
                prgComputerLife.setValue(compHp);
                prgPlayerLife.setValue(playerHp);
            }else if(prgPlayerLife.getValue() == 0 ){
                JOptionPane.showMessageDialog(null, "You Lost!, Reset The game.", "Jack n' Poy Game", JOptionPane.INFORMATION_MESSAGE);
                compHp=100;
                compWins++;
                playerHp=100;
                lblComWins.setText(compWins+"");
                prgComputerLife.setValue(compHp);
                prgPlayerLife.setValue(playerHp);
            }
        }
        
        btnFight.setEnabled(false);
        
        
    }//GEN-LAST:event_btnFightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFight;
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel lblComWins;
    private javax.swing.JLabel lblComp;
    private javax.swing.JLabel lblComputerPick;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblPlayerPick;
    private javax.swing.JLabel lblPlayerWins;
    private javax.swing.JLabel lblWin;
    private javax.swing.JProgressBar prgComputerLife;
    private javax.swing.JProgressBar prgPlayerLife;
    // End of variables declaration//GEN-END:variables
}